apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-ntfy-config
  namespace: monitoring
data:
  config.yml: |
    http:
      addr: :8000
    log:
      level: info
      format: json
    ntfy:
      baseurl: https://ntfy.sh
      notification:
        topic: jack-smarthome-050101
        priority: |
          status == "firing" ? (labels.severity == "critical" ? "urgent" : "high") : "low"
        tags:
          - tag: rotating_light
            condition: status == "firing"
          - tag: white_check_mark
            condition: status == "resolved"
        templates:
          title: |
            {{ if eq .Status "resolved" }}Resolved: {{ end }}{{ .Labels.alertname }}{{ if .Labels.namespace }} ({{ .Labels.namespace }}){{ end }}
          description: |
            {{ if .Annotations.summary }}{{ .Annotations.summary }}{{ end }}
            {{ if .Annotations.description }}
            {{ .Annotations.description }}{{ end }}
