apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alertmanager
  namespace: argocd
spec:
  source:
    repoURL: 'https://github.com/Jacko10101/smart-home.git'
    path: applications/alertmanager
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  project: default
