apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mosquitto
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Jacko10101/smart-home.git
    targetRevision: HEAD
    path: applications/mosquitto
  destination:
    server: https://kubernetes.default.svc
    namespace: mosquitto
