prometheus:
  prometheusSpec:
    retention: 30d
  service:
    type: NodePort
    port: 9090
    nodePort: 30090
    targetPort: 9090

grafana:
  service:
    type: NodePort
    nodePort: 31295

alertmanager:
  alertmanagerSpec:
    service:
      type: NodePort
      nodePort: 30723