apiVersion: v1
kind: ServiceAccount
metadata:
  name: tailscale
  namespace: tailscale
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tailscale
rules:
- apiGroups: [""]
  resources: ["services", "services/status", "endpoints", "events"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tailscale
subjects:
- kind: ServiceAccount
  name: tailscale
  namespace: tailscale
roleRef:
  kind: ClusterRole
  name: tailscale
  apiGroup: rbac.authorization.k8s.io