apiVersion: v1
kind: Service
metadata:
  name: zigbee2mqtt
  namespace: zigbee
  annotations:
    tailscale.com/expose: "true"
  labels:
    app.kubernetes.io/instance: zigbee2mqtt
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: zigbee2mqtt