apiVersion: v1
kind: PersistentVolume
metadata:
  name: zigbee2mqtt-data
  namespace: zigbee
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /zigbee2mqtt-data
    type: DirectoryOrCreate
  storageClassName: local-storage
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zigbee2mqtt-data
  namespace: zigbee
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-storage