apiVersion: v1
kind: Secret
metadata:
  name: home-assistant-token
  namespace: monitoring
type: Opaque
data:
  token: ZXlKaGJHY2lPaUpJVXpJMU5pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SnBjM01pT2lJNFpqSTVNRGcxWkRnM01UYzBaVGRqWVRZMk0yRTRNR015T1RnNU56RTROQ0lzSW1saGRDSTZNVGN6TlRreE1qRTNOeXdpWlhod0lqb3lNRFV4TWpjeU1UYzNmUS4yNndnVHlwYlkwUFluRF8zbFZQTXJ1SmVnTnBYRURrUEx0VmxqWmhwSDRz