apiVersion: v1
kind: Service
metadata:
  name: home-assistant
  namespace: home-assistant
  annotations:
    tailscale.com/expose: "true"
spec:
  type: ClusterIP
  ports:
    - port: 8123
      targetPort: 8123
      name: http
  selector:
    app: home-assistant