apiVersion: v1
kind: Service
metadata:
  name: home-assistant
  namespace: home-assistant
  labels:
    app: home-assistant
    release: prometheus
spec:
  ports:
    - port: 8123
      targetPort: 8123
      name: http
  selector:
    app: home-assistant