apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: home-assistant
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: home-assistant
  endpoints:
    - port: http
      path: /api/prometheus
      interval: 30s
      bearerTokenSecret:
        name: home-assistant-token
        key: token
  namespaceSelector:
    matchNames:
      - home-assistant