apiVersion: v1
kind: Service
metadata:
  name: home-assistant
  namespace: home-assistant
  annotations:
    tailscale.com/expose: "true"
  labels:
    app.kubernetes.io/instance: home-assistant
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8123
      targetPort: 8123
  selector:
    app: home-assistant